"""
Vendor spend summary as a shareable PDF.

One A4 page listing every vendor: invoice count, total spend, and the
last invoice date, biggest spend first, with an account total. Built
with PyMuPDF (same engine as the statement export) so it can be
shared straight into WhatsApp / email from the Vendors page.
"""
from __future__ import annotations

import datetime as dt
from typing import Any

import pymupdf

from app.database import vendor_spend_summary

_PAGE_W, _PAGE_H = 595, 842  # A4 points
_MARGIN = 54
_BLUE = (0.145, 0.388, 0.922)
_DARK = (0.06, 0.09, 0.16)
_MUTED = (0.39, 0.45, 0.55)
_ROW_LINE = (0.89, 0.91, 0.94)


def _fmt_inr(value: float) -> str:
    s = f"{value:,.2f}"
    return f"Rs {s}"


def build_vendor_summary_pdf(user_id: str, owner_email: str = "") -> bytes:
    """Render the account's vendor spend summary as a one-page PDF."""
    rows: list[dict[str, Any]] = vendor_spend_summary(user_id)
    total = sum(row.get("total_spend", 0.0) for row in rows)

    doc = pymupdf.open()
    page = doc.new_page(width=_PAGE_W, height=_PAGE_H)

    y = _MARGIN
    page.insert_text((_MARGIN, y), "Vendor spend summary", fontsize=20, fontname="hebo", color=_DARK)
    y += 18
    subtitle = dt.date.today().strftime("Generated %d %b %Y")
    if owner_email:
        subtitle += f"  |  {owner_email}"
    page.insert_text((_MARGIN, y), subtitle, fontsize=9, fontname="helv", color=_MUTED)
    y += 24

    col_vendor = _MARGIN
    col_invoices = _PAGE_W - _MARGIN - 300
    col_last = _PAGE_W - _MARGIN - 170
    col_spend = _PAGE_W - _MARGIN

    page.insert_text((col_vendor, y), "Vendor", fontsize=9, fontname="hebo", color=_MUTED)
    page.insert_text((col_invoices, y), "Invoices", fontsize=9, fontname="hebo", color=_MUTED)
    page.insert_text((col_last, y), "Last invoice", fontsize=9, fontname="hebo", color=_MUTED)
    page.insert_text((col_spend - 60, y), "Total spend", fontsize=9, fontname="hebo", color=_MUTED)
    y += 6
    page.draw_line(pymupdf.Point(_MARGIN, y), pymupdf.Point(_PAGE_W - _MARGIN, y), color=_BLUE, width=1.2)
    y += 18

    if not rows:
        page.insert_text((_MARGIN, y + 12), "No invoices yet.", fontsize=11, fontname="helv", color=_MUTED)

    for row in rows:
        if y > _PAGE_H - _MARGIN - 30:  # safety; one page is plenty for this data
            break
        name = str(row.get("vendor") or "(unknown)")
        if len(name) > 34:
            name = name[:31] + "..."
        last = row.get("last_invoice") or "-"
        spend = _fmt_inr(float(row.get("total_spend") or 0))

        page.insert_text((col_vendor, y), name, fontsize=10, fontname="helv", color=_DARK)
        page.insert_text((col_invoices, y), str(row.get("invoice_count", 0)), fontsize=10, fontname="helv", color=_DARK)
        page.insert_text((col_last, y), last, fontsize=10, fontname="helv", color=_DARK)
        page.insert_text((col_spend - len(spend) * 5.4, y), spend, fontsize=10, fontname="hebo", color=_DARK)
        y += 6
        page.draw_line(
            pymupdf.Point(_MARGIN, y), pymupdf.Point(_PAGE_W - _MARGIN, y), color=_ROW_LINE, width=0.6
        )
        y += 18

    y += 10
    total_label = f"Total across {len(rows)} vendor(s): {_fmt_inr(total)}"
    page.insert_text((_MARGIN, y), total_label, fontsize=11, fontname="hebo", color=_BLUE)

    footer = "Generated by Invoxa - invoice automation for Indian micro-businesses"
    page.insert_text((_MARGIN, _PAGE_H - _MARGIN + 14), footer, fontsize=7.5, fontname="helv", color=_MUTED)

    return doc.tobytes(deflate=True, garbage=3)
